"""Create initial schema

Revision ID: a122c654efe3
Revises: 
Create Date: 2025-05-07 14:14:39.026755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a122c654efe3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'total_amount',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('orders', 'total_amount',
               existing_type=sa.FLOAT(),
               nullable=True)
    # ### end Alembic commands ###
